project_id = "vraqbzokccvqhthixoof"

[functions.clash-royale-api]
verify_jwt = false

[functions.analyze-player]
verify_jwt = false

[functions.analyze-match]
verify_jwt = false

[functions.analyze-deck]
verify_jwt = false

[functions.sync-card-collection]
verify_jwt = false

[functions.analyze-deck-builder]
verify_jwt = false